Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8")
install.packages("dagitty")
devtools::install_github("stan-dev/cmdstanr")
cmdstanr::install_cmdstan()
devtools::install_github("rmcelreath/rethinking")
